---
title: "Leadership Learning Group"
subtitle: "A group dedicated to providing a space to learn and share knowledge about leadership, building groups or teams, and general organizational design and culture."
date: last-modified
author: Luke Johnston
---

::: callout-caution
This is a work in progress. The content of this page is not final and
will be regularly updated as the group develops.
:::

::: callout-note
This website is aimed at employees at Steno Aarhus or Aarhus University
who are interested in leadership or are in leadership positions.
:::

There are many resources for learning about more fundamental research
skills and knowledge, such as the [Epi
Stats](https://steno-aarhus.github.io/epi-stats/) group or the regular
Steno Thursdays or individual research group meetings. But for skills
and knowledge that are needed further in your career, like leadership,
there are fewer resources. Especially when it comes to peer learning and
knowledge sharing. This is the motivation for starting this group.

## Purpose

The purpose of this group is to provide a space for learning and sharing
knowledge about leadership and group/team/organisational design and
culture. It will be primarily used to informally discuss and share
things we've learned/read about or resources we've found useful when it
comes to leadership. Importantly, this will be a space to critically
reflect on current practices and how we can improve things, based on
science and evidence.

This is mainly a space to share and discuss things we've read or
learned, that we could potentially apply in our own
groups/teams/organizations. This is not necessarily a space about our
own individual experiences and how we feel we're doing as leaders [^1].
This is about knowledge, skills, critical reflection, and ways to
improve. However, we can use this space to discuss personal challenges
and struggles, to get peers' perspective and advice on.

[^1]: Though we could organise "peer feedback" or "peer coaching"
    sessions at some point in the future, if there is interest.

The main audience for this group is anyone who is currently in a
leadership position or who is interested in becoming a leader in the
future. It's also, of course, open to anyone who is just generally
interested in these topics!

## Things to learn

This section is meant to be a list of topics or things we could
potentially read or discuss during the group sessions. As we build this
group, we'll add more to this section. For now, it's things I've read or
found interesting that I think others might find interesting too, or
that I feel would be interesting to discuss.

### Books

While several of these are aimed at making software, they all contain
valuable insights into leadership, building healthy team dynamics, and
improving/designing organizational culture. Both software development
and research are creative knowledge work, so many of the same principles
apply to both domains.

-   [Team Topologies: Organizing Business and Technology Teams for Fast
    Flow](https://teamtopologies.com/book) is an excellent book (and
    [website](https://www.teamtopologies.com/)) that discusses effective
    ways of building teams and getting work done. While the focus is on
    software teams, the principles are generic enough to apply to any
    knowledge work.
-   [Accelerate: Building and scaling high performing technology
    organizations](https://www.goodreads.com/book/show/35747076-accelerate)
    is a book that provides evidence-based insights into how to build
    effective knowledge work organizations. It is based on years of
    research and provides practical guidance for leaders.
-   [The Manager's Path: A Guide for Tech Leaders Navigating Growth and
    Change](https://www.goodreads.com/book/show/33369254-the-manager-s-path)
    is a book that provides practical advice for tech/knowledge work
    leaders at all levels, from managing teams to leading organizations.
-   [Kanban from the Inside: Understand the Kanban Method, Integrate It
    into Your Work, and Transform Your
    Team](https://www.goodreads.com/book/show/23162381-kanban-from-the-inside)
    is a book that provides a comprehensive overview of the Kanban
    method, which is a popular approach to managing work in knowledge
    work environments.

### Articles

We will add articles here as we review them.

## Calendar

{{< include _calendar.qmd >}}

## Contact

-   [Luke Johnston](mailto:lwjohnst@clin.au.dk) sets up, organises, and
    runs this group.
